### ISSUE TITLE
flageval-serving 中的cli.py中的main函数

### ISSUE THREAD

**Issue by pxyfxun** [flageval-baai/FlagEval#10]
python的main函数的写法：

`def main():
    cli()`

不应该是：
`if __name__ == "__main__":
    cli()`
吗？

**Comment by asyncat** [comment]
这里并不是用于直接执行的 Python 脚本如 `python xxx.py` 这种场景，而是用于 `console_scripts` 入口在包安装的时候同时安装一个命令使用，所以没有使用 `if __name__ == "__main__"` 这种写法。

**Comment by asyncat** [comment]
可以参考 [The console_scripts Entry Point](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point)
