### ISSUE TITLE
关于flageval-serving的问题

### ISSUE THREAD

**Issue by pxyfxun** [flageval-baai/FlagEval#11]
请问如果想在本地离线进行，对自然语言模型的评价，可以用flageval-serving 模块，在本地进行吗？

还是说离线测试，必须把模型和代码上传到flageval平台？https://flageval.baai.ac.cn/#/rule?m=2

**Comment by xiyang85** [comment]
flageval-serving是部署推理服务的模块，可以使用该模块在本地部署推理服务。但如果要进行离线模型评价的话，还是需要把代码和模型上传到flageval平台才可以进行。
