### ISSUE TITLE
关于排行榜的疑问

### ISSUE THREAD

**Issue by pxyfxun** [flageval-baai/FlagEval#15]
请问，排行榜中的小数是否是得分？

ChatGLM-6B在中文选择问答Chinese_MMLU数据集下的得分是0.212，是否可以理解为，满分100分的话，得分为21.2分？也就是说，100道题，只答对了21道?

**Comment by xiyang85** [comment]
排行榜中的得分是准确性的得分，具体的定义可以参考官网中评测指标的定义：https://flageval.baai.ac.cn/#/taskIntro?t=zh_qa&m=1
