### ISSUE TITLE
文生图模型评估方法

### ISSUE THREAD

**Issue by cyy-1234** [flageval-baai/FlagEval#19]
你好，文生图模型评估方法有进展吗，比如只针对某一类的生成图，例如，生成人的

**Comment by xuanricheng** [comment]
目前还没有针对文生图某一类的新的进展，后续我们会在我们的 [flageval 网站](https://flageval.baai.ac.cn/#/home) 更新多模态的评测结果

**Comment by Youngon** [comment]
请问如何使用ImageEval评估文生图模型，比如我先用paitiprompts生成了图，标注任务该给这些图做何种打标，并且如何计算和gt en.csv的指标？求指导
