### ISSUE TITLE
请问什么时候能发布评估语言模型的框架，针对自然语言处理任务

### ISSUE THREAD

**Issue by Yun-Peng-Wang** [flageval-baai/FlagEval#2]
请问什么时候能发布评估语言模型的框架，针对自然语言处理任务

**Comment by xiyang85** [comment]
预计在5月底6月初的时候会发布评语言模型的框架，感谢关注

**Comment by xiyang85** [comment]
语言模型评测框架已经发布，欢迎关注，更多细节请见：https://zhuanlan.zhihu.com/p/636945982
