### ISSUE TITLE
关于最新榜单中通义千问chat版本的评测疑问

### ISSUE THREAD

**Issue by qiufengyuyi** [flageval-baai/FlagEval#20]
不知道这块评测具体细节，但是大部分模型在中文客观题上chat版比base版有提升，反而千问是断崖式下滑（0.596-》0.070），从结果上来看有点异常。跟opencompass那边的评测的结果也有较大出入。
        建议还是再确认一下评测细节？是不是prompt啥的有点问题

**Comment by jxst539246** [comment]
![image](https://github.com/FlagOpen/FlagEval/assets/17763236/8fa811cf-c54c-47d4-b522-a971510c5db3)

同问，看起来sft模型的评测都不大对

**Comment by tonysy** [comment]
If you are curious about the evaluation protocol of LLM. Welcome to OpenCompass (https://opencompass.org.cn/) for information of LLM, which provides all details of evaluation. We will support more exicted features(long-context, coding, tool use , etc) soon. Star our project for more updates.

**Comment by xiyang85** [comment]
在客观评测上，不论是base模型还是sft模型，FlagEval均使用相同的prompt（5-shot）作为输入。

考虑到评测结果的权威性和严谨性，榜上的评测结果均会经过人工抽样审核。Qwen-chat-7b在指令理解方面的能力确实是较base模型有所下降，这也是为什么客观评测分数较低的原因。但要注意的是Qwen-chat-7b的对话能力非常优秀，所以主观评测的分数非常高。

Guanaco-7b的结果是类似的原因。

Moss-moon-sft-16b结果中标为“-”对应的是英文客观数据集，Moss本身是中文模型，所以英文数据集是没测的。

FlagEval竭诚期待榜上各个模型通过优化可以刷新现有成绩，达到“以评促优”的目的。
