### ISSUE TITLE
FlagEval基础准备工作需要哪些？

### ISSUE THREAD

**Issue by Micla-SHL** [flageval-baai/FlagEval#23]
你好，我预装了FlagEval. 它应该是没有问题的。那我该如何使用呢？ 前期是先去玩AltCLIP这类模型？https://github.com/FlagOpen/FlagEval/blob/master/imageEval/README.md 从这份readme来看，这份评估工具是专为多模态模型AltCLIP之类准备的吗？它不适用于Aquila。我这么理解有出入吗？

**Comment by Micla-SHL** [comment]
update: 

![2023-10-29 01-35-46屏幕截图](https://github.com/FlagOpen/FlagEval/assets/44502050/6212b0a1-264e-4e2f-af02-ece568435a39)
我的torch是2.1.0+cu118 ,   我的想法是requirements.txt 指定的torchvision版本是有意义的吗？因为执行安装脚本会修改我原先的torch版本
![2023-10-29 01-37-00屏幕截图](https://github.com/FlagOpen/FlagEval/assets/44502050/12fa9456-402b-46f4-a35b-c16bb58e7ea0)
原始 torchvision将我的torch降级到1.11.    相对而言我的torch、torchvision版本过高会有一些已知的错误？还是文中指定的torchvision版本是依据你们的eval环境而言，如果是后者，我想应该可以不去指定torchvision，因为我这暂时的测试案例是ok的

**Comment by xiyang85** [comment]
imageEval是面向文生图任务的一个测试集，不适合评Aquila。
您提到的关于torch版本的问题，我们会酌情修改，多谢！

**Comment by xiyang85** [comment]
更多的关于语言模型评测的结果可以登录FlagEval平台 https://flageval.baai.ac.cn/#/home

**Comment by Micla-SHL** [comment]
Thanks

**Comment by Youngon** [comment]
> imageEval是面向文生图任务的一个测试集，不适合评Aquila。 您提到的关于torch版本的问题，我们会酌情修改，多谢！

请问如何使用ImageEval评估文生图模型，比如我先用paitiprompts生成了图，标注任务该给这些图做何种打标，并且如何计算和gt en.csv的指标？求指导
