### ISSUE TITLE
What are `LLSRC`, `SLSRC`, `SLPWC`, and `SLPWC` benchmarks?

### ISSUE THREAD

**Issue by zhimin-z** [flageval-baai/FlagEval#25]
https://arxiv.org/abs/2112.15093
https://aclanthology.org/2021.emnlp-main.306/
是这个吗

**Comment by zhimin-z** [comment]
https://arxiv.org/abs/2112.15093
https://aclanthology.org/2021.emnlp-main.306/
是这个吗

**Comment by siyu-hu** [comment]
Nope, C-SEM dataset 👉 https://github.com/FlagOpen/FlagEval/tree/master/csem , I will add README.md as soon as possible.  C-SEM is a new dataset conducted by Peking University and Minjiang College in 2023.  #27  The sub-evaluation items of C-SEM are: Lexical Level Semantic Relationship Classification (LLSRC), Sentence Level Semantic Relationship Classification (SLSRC), Sentence Level Polysemous Words Classification (SLPWC), and Sentence Level Rhetoric Figure Classification (SLRFC).

Note: To ensure fair and impartial evaluation results and prevent the risk of evaluation set leakage, the C-SEM evaluation set used on the **FlagEval official website ([flageval.baai.ac.cn](https://flageval.baai.ac.cn/#/trending))** will be asynchronously updated with the open-source version. The current FlagEval version, compared to the open-source one, has more questions, richer formats, and uses a 5-shot formation for evaluation, referencing the HELM approach.
