### ISSUE TITLE
Are those evaluation metrics all `accuracy`?

### ISSUE THREAD

**Issue by zhimin-z** [flageval-baai/FlagEval#28]
![image](https://github.com/FlagOpen/FlagEval/assets/8592144/cf2e55fa-1e70-454f-860f-d88bbce8a272)
The code is a bit hard to understand:
![image](https://github.com/FlagOpen/FlagEval/assets/8592144/1cd2a28b-9b89-4500-a474-1927fa14b5f3)
@xuanricheng

**Comment by xuanricheng** [comment]
This code is not part of the same system as our website's leaderboard; 
"Supported_metrics" is used in mCLIPeval, which is a multi-modal evaluation tool. It is different from [FlagEval](https://flageval.baai.ac.cn/#/trending). mCLIPeval has not yet been launched on our FlagEval website's leaderboard.

**Comment by zhimin-z** [comment]
So what metrics are shown after all in FlagEval leaderboards?

**Comment by xuanricheng** [comment]
> So what metrics are shown after all in FlagEval leaderboards?

This code is not related to the leaderboard. The leaderboard only uses accuracy
