### ISSUE TITLE
Why include empty evaluation result?

### ISSUE THREAD

**Issue by zhimin-z** [flageval-baai/FlagEval#30]
![image](https://github.com/FlagOpen/FlagEval/assets/8592144/933e5afd-6e03-4468-ba71-072381fc53b2)
![image](https://github.com/FlagOpen/FlagEval/assets/8592144/cdaf8925-95fd-449f-8410-290d176d94a5)

**Comment by xuanricheng** [comment]
This was an internal test result for our upcoming launch of the Multi-modal leaderboard, which was not supposed to be displayed. It has now been removed. 
Thank you for helping us identify this bug.
