### ISSUE TITLE
Are all the evaluation results on the leaderboard `zero-shot`?

### ISSUE THREAD

**Issue by zhimin-z** [flageval-baai/FlagEval#31]
Where to find the shot configuration for each benchmark? @xuanricheng

**Comment by xuanricheng** [comment]
Not all of them

**Comment by xuanricheng** [comment]
> Where to find the shot configuration for each benchmark? @xuanricheng
Part of the configuration can refer to our prompt example 
https://flageval.baai.ac.cn/#/taskIntro?t=zh_qa&m=prompt
