### ISSUE TITLE
Where are the evaluation tasks?

### ISSUE THREAD

**Issue by zhimin-z** [flageval-baai/FlagEval#33]
![image](https://github.com/FlagOpen/FlagEval/assets/8592144/5aca4abc-e73a-4839-9ffa-fac1bacfaad1)

**Comment by xuanricheng** [comment]
We Use Chrome browser has this task, what browser are you using? Many other questions can be added directly to our wechat group chat
![IMG_4158](https://github.com/FlagOpen/FlagEval/assets/6874101/d0698a6c-28ce-4bc9-84e9-21a6d6f85e98)

**Comment by fggggg7142** [comment]
Thanks. We will fix this week

**Comment by zhimin-z** [comment]
![image](https://github.com/FlagOpen/FlagEval/assets/8592144/198f529f-1aa7-4262-bac1-046f23cb72a2)
I am using Chrome as well: Version 120.0.6099.129 (Official Build) (arm64)

**Comment by zhimin-z** [comment]
Closed since the options did appear afterwards.
