### ISSUE TITLE
Why is the audio leaderboard inaccessible?

### ISSUE THREAD

**Issue by zhimin-z** [flageval-baai/FlagEval#37]
Check https://flageval.baai.ac.cn/#/leaderboard but found:
![image](https://github.com/FlagOpen/FlagEval/assets/8592144/b35a187c-88b7-4fbf-aed4-883873222d26)

**Comment by xuanricheng** [comment]
This is a feature that will be released soon and is also introduced on the homepage

**Comment by zhimin-z** [comment]
Closed since they changed the whole layout of leaderboard recently.
<img width="1387" alt="image" src="https://github.com/user-attachments/assets/757ceceb-ee8a-43dd-a9ab-f2ee65edeed6">
