### ISSUE TITLE
请问关于evaluation具体实现细节相关问题

### ISSUE THREAD

**Issue by zyzheng17** [flageval-baai/FlagEval#7]
在知乎文章中您提到，"我们利用 ImageEval-prompt 对知名文生图模型进行评测，针对每个Prompt，让每个模型生成8张图片，标注者在未看到Prompt的情况下对8张图片进行排序，并选择前三张排名较高的图片，最后标注这三张图片是否正确表达了Prompt的关键信息。"

在最后一步，即“标注这三张图片是否正确表达了Prompt的关键信息”，这里的具体操作是什么呢？

例如，对于prompt“穿着华丽的衣服的女士坐在椅子上，素描”，其颜色，性别，五官的标注分别为0，1，2，那么评测人员是否只需要根据标注维度（无视prompt）判断生成的图片是否符合各个维度的标注结果（0未出现，1简单考察，2复杂考察），还是评测人员同时可以看到标注与prompt，再根据标注回到prompt判断图片表达是否准确？例如，标注人员已知性别标注为1，那么根据prompt需要自行判断生成图片内容是否符合prompt中描述的“女士”一项。如果评测人员采取第二种方法，那么对于标注1简短考察与2复杂考察，它们在评测流程中的区别是什么？

最后，在“标注维度说明”一节中，您给出了每一个子维度的具体标注，请问数据集中是否每条数据的每个子维度均有具体标注供评测人员参考？还是目前开源的数据集已经是所有内容了？

感谢您的回答！

**Comment by xiyang85** [comment]
1. 在最后一步中，评测人员同时可以看到prompt和prompt的标注，再根据标注的内容来判断生成的图片中是否含有符合prompt的内容。即您提到的第二种方法。
2. 标注1 简单考察和标注2复杂考察，在评测过程中的操作是相同的，1和2的区别仅在于表示生成的难度。
3. 目前开源的数据集已经是所有内容了。

感谢您的关注，如果有任何建议和问题，欢迎交流，或者发邮件至flageval@baai.ac.cn中。
