### ISSUE TITLE
请问现有的榜单是否有参考价值？Mean的值是如何计算的？

### ISSUE THREAD

**Issue by Youning97** [flageval-baai/FlagEval#8]
为什么我算出平均值和榜单给的不一样？有甲醛吗？权重是多少？

**Comment by xiyang85** [comment]
感谢您对天秤的关注！
每个平均值是对应的所有数据集指标的算数平均，例如中文Mean(客观)是指所有中文客观数据集（中文选择问答&中文文本分类）指标的算数平均。Mean（主观+客观）是指所有数据集指标的算数平均，而不是Mean（客观）与Mean（主观）的平均。
感谢您的提问，我们会在排行榜的下一个版本中增加相关的解释说明。
